import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">

      <body
        className= {`${geistSans.variable} ${geistMono.variable} antialiased`} 
      >
        <main className="flex justify-center px-4">
          <div className="w-full h-full max-w-md sm:max-w-lg md:max-w-xl lg:max-w-2xl bg-white rounded-2xl shadow-md flex flex-col">
            <Header />
            <div className="flex-1 overflow-y-auto p-4 sm:p-6">
              {children}
            </div>
          </div>
        </main>
      </body>
    </html>
  );
}
