import type { Metadata } from "next";
import localFont from 'next/font/local'
import "./globals.css";
import Header from "@/components/Header";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const byekanFont = localFont({
  src: '../fonts/BYekanPlus-Bold.ttf',
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">

      <body
        className= {byekanFont.className} 
      >
        <main className="flex justify-center px-4">
          <div className="w-full h-full max-w-md sm:max-w-lg md:max-w-xl lg:max-w-2xl bg-white sm:shadow-md flex flex-col">
            <Header />
            <div className="flex-1 overflow-y-auto p-4 sm:p-6">
              {children}
            </div>
          </div>
        </main>
      </body>
    </html>
  );
}
